// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Device struct {
	ID         string    `json:"id"`
	UserID     string    `json:"user_id"`
	Name       string    `json:"name"`
	Platform   string    `json:"platform"`
	LastSeenAt time.Time `json:"last_seen_at"`
	CreatedAt  time.Time `json:"created_at"`
}

type Node struct {
	ID        string         `json:"id"`
	Kind      string         `json:"kind"`
	Region    string         `json:"region"`
	City      string         `json:"city"`
	LatencyMs int32          `json:"latency_ms"`
	Load      float32        `json:"load"`
	Tier      sql.NullString `json:"tier"`
	Label     sql.NullString `json:"label"`
	StaticIp  sql.NullString `json:"static_ip"`
	ExpiresAt sql.NullTime   `json:"expires_at"`
	OwnerID   uuid.NullUUID  `json:"owner_id"`
}

type RefreshToken struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	Revoked   bool      `json:"revoked"`
	CreatedAt time.Time `json:"created_at"`
}

type Subscription struct {
	UserID      string       `json:"user_id"`
	Plan        string       `json:"plan"`
	Status      string       `json:"status"`
	ExpiresAt   sql.NullTime `json:"expires_at"`
	DeviceLimit int32        `json:"device_limit"`
}

type User struct {
	ID           string    `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}
