// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package store

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countDevices = `-- name: CountDevices :one
SELECT count(*) FROM devices WHERE user_id = $1
`

func (q *Queries) CountDevices(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDevices, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (user_id, name, platform)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, platform, last_seen_at, created_at
`

type CreateDeviceParams struct {
	UserID   string `json:"user_id"`
	Name     string `json:"name"`
	Platform string `json:"platform"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRowContext(ctx, createDevice, arg.UserID, arg.Name, arg.Platform)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Platform,
		&i.LastSeenAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
`

type CreateRefreshTokenParams struct {
	UserID    string    `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createSubscription = `-- name: CreateSubscription :exec
INSERT INTO subscriptions (user_id, plan, status, expires_at, device_limit)
VALUES ($1, $2, $3, $4, $5)
`

type CreateSubscriptionParams struct {
	UserID      string       `json:"user_id"`
	Plan        string       `json:"plan"`
	Status      string       `json:"status"`
	ExpiresAt   sql.NullTime `json:"expires_at"`
	DeviceLimit int32        `json:"device_limit"`
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) error {
	_, err := q.db.ExecContext(ctx, createSubscription,
		arg.UserID,
		arg.Plan,
		arg.Status,
		arg.ExpiresAt,
		arg.DeviceLimit,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash)
VALUES ($1, $2)
RETURNING id, email, created_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

type CreateUserRow struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.PasswordHash)
	var i CreateUserRow
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM devices WHERE id = $1 AND user_id = $2
`

type DeleteDeviceParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteDevice(ctx context.Context, arg DeleteDeviceParams) error {
	_, err := q.db.ExecContext(ctx, deleteDevice, arg.ID, arg.UserID)
	return err
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_hash, expires_at, revoked
FROM refresh_tokens WHERE token_hash = $1
`

type GetRefreshTokenRow struct {
	ID        string    `json:"id"`
	UserID    string    `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	Revoked   bool      `json:"revoked"`
}

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (GetRefreshTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getRefreshToken, tokenHash)
	var i GetRefreshTokenRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.Revoked,
	)
	return i, err
}

const getSubscription = `-- name: GetSubscription :one
SELECT user_id, plan, status, expires_at, device_limit
FROM subscriptions WHERE user_id = $1
`

func (q *Queries) GetSubscription(ctx context.Context, userID string) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscription, userID)
	var i Subscription
	err := row.Scan(
		&i.UserID,
		&i.Plan,
		&i.Status,
		&i.ExpiresAt,
		&i.DeviceLimit,
	)
	return i, err
}

const getSubscriptionForUpdate = `-- name: GetSubscriptionForUpdate :one
SELECT user_id, plan, status, expires_at, device_limit
FROM subscriptions WHERE user_id = $1 FOR UPDATE
`

func (q *Queries) GetSubscriptionForUpdate(ctx context.Context, userID string) (Subscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionForUpdate, userID)
	var i Subscription
	err := row.Scan(
		&i.UserID,
		&i.Plan,
		&i.Status,
		&i.ExpiresAt,
		&i.DeviceLimit,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, user_id, name, platform, last_seen_at, created_at
FROM devices WHERE user_id = $1 ORDER BY created_at
`

func (q *Queries) ListDevices(ctx context.Context, userID string) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevices, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Platform,
			&i.LastSeenAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesForUser = `-- name: ListNodesForUser :many
SELECT id, kind, region, city, latency_ms, load, tier, label, static_ip, expires_at, owner_id
FROM nodes
WHERE owner_id IS NULL OR owner_id = $1
ORDER BY kind, latency_ms
`

func (q *Queries) ListNodesForUser(ctx context.Context, ownerID uuid.NullUUID) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listNodesForUser, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Region,
			&i.City,
			&i.LatencyMs,
			&i.Load,
			&i.Tier,
			&i.Label,
			&i.StaticIp,
			&i.ExpiresAt,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSharedNodesByScore = `-- name: ListSharedNodesByScore :many
SELECT id, kind, region, city, latency_ms, load, tier, label, static_ip, expires_at, owner_id
FROM nodes
WHERE owner_id IS NULL
ORDER BY latency_ms ASC, load ASC
LIMIT 1
`

func (q *Queries) ListSharedNodesByScore(ctx context.Context) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, listSharedNodesByScore)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Region,
			&i.City,
			&i.LatencyMs,
			&i.Load,
			&i.Tier,
			&i.Label,
			&i.StaticIp,
			&i.ExpiresAt,
			&i.OwnerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllUserTokens = `-- name: RevokeAllUserTokens :exec
UPDATE refresh_tokens SET revoked = true WHERE user_id = $1
`

func (q *Queries) RevokeAllUserTokens(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, revokeAllUserTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked = true WHERE token_hash = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.ExecContext(ctx, revokeRefreshToken, tokenHash)
	return err
}

const seedNode = `-- name: SeedNode :exec
INSERT INTO nodes (kind, region, city, latency_ms, load, tier, label, static_ip, expires_at, owner_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type SeedNodeParams struct {
	Kind      string         `json:"kind"`
	Region    string         `json:"region"`
	City      string         `json:"city"`
	LatencyMs int32          `json:"latency_ms"`
	Load      float32        `json:"load"`
	Tier      sql.NullString `json:"tier"`
	Label     sql.NullString `json:"label"`
	StaticIp  sql.NullString `json:"static_ip"`
	ExpiresAt sql.NullTime   `json:"expires_at"`
	OwnerID   uuid.NullUUID  `json:"owner_id"`
}

func (q *Queries) SeedNode(ctx context.Context, arg SeedNodeParams) error {
	_, err := q.db.ExecContext(ctx, seedNode,
		arg.Kind,
		arg.Region,
		arg.City,
		arg.LatencyMs,
		arg.Load,
		arg.Tier,
		arg.Label,
		arg.StaticIp,
		arg.ExpiresAt,
		arg.OwnerID,
	)
	return err
}

const updatePassword = `-- name: UpdatePassword :exec
UPDATE users SET password_hash = $2 WHERE id = $1
`

type UpdatePasswordParams struct {
	ID           string `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error {
	_, err := q.db.ExecContext(ctx, updatePassword, arg.ID, arg.PasswordHash)
	return err
}
